import { generateGuard } from "typing-assets";
import { Exception } from "../typing/Exception";

// before generateGuard function was used to create guard
// but now guard generated by library function has got bug (https://github.com/LCcodder/typing-assets/issues/2)
// so for now on it is manually created type guard
export const isException = (target: unknown): target is Exception => {
    return target && typeof (target as Exception)["message"] === 'string'
}