name: Run e2e and unit tests

on: 
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

jobs:        

  tests:
    runs-on: ubuntu-latest
    steps:
      # Jest unit tests run

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '18'

      - name: Run npm install
        run: npm i
      - name: Run Jest unit tests
        run: npm test

      # e2e postman tests run

      - uses: actions/checkout@v2
      - name: Build servies
        run: docker compose up -d
      


      - uses: actions/setup-node@v1
        with:
          node-version: '18'
      - run: npm install -g newman

      - run: npm install -g newman

      
      - name: Run Postman collection tests
        run: newman run "tests/e2e/api_v1.postman_collection.json"


            


